server:
  port: 0

spring:
  application:
    name: job-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

application:
  title: Job Service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: false
  health:
    defaults:
      enabled: true
    db:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

management.endpoint.health.group.liveness.include=livenessState
management.endpoint.health.group.readiness.include=readinessState,db,kafka,feignClients
