spring:
  config:
    activate:
      on-profile: prod

jwt:
  secret: ${JWT_SECRET}

server:
  error:
    include-stacktrace: never
    include-message: never

logging:
  level:
    com.safalifter: INFO
