server:
  port: 0

spring:
  application:
    name: file-storage
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

file:
  storage:
    path: ${user.home}/spring-boot-microservices/file-storage

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: false
  health:
    defaults:
      enabled: true
    db:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

management.endpoint.health.group.liveness.include=livenessState
management.endpoint.health.group.readiness.include=readinessState,db,fileStorage
